; Inno Setup script for Funkit VST3 installer
; Generated by GitHub Copilot

[Setup]
AppName=Funkit VST3
AppVersion=1.0.0
DefaultDirName={pf}\Common Files\VST3
DefaultGroupName=Funkit
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=FunkitInstaller
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
#define SourceVST3 "C:\Users\elifa\git\funkit\Builds\VisualStudio2026\x64\Release\VST3\Funkit.vst3\Contents\x86_64-win"

[Files]
; Copy the entire .vst3 bundle folder from the dist directory into the Common Files\VST3 folder
Source: "{#SourceVST3}\*"; DestDir: "{pf}\Common Files\VST3\"; Flags: recursesubdirs createallsubdirs restartreplace

[Icons]
Name: "{group}\Funkit (Docs)"; Filename: "{app}\..\README.txt"

[Run]
; No automatic run action required for a VST installer

[Code]

